controller_list:
  - name: fake_up_controller
    joints:
      - Upper_joint
  - name: fake_ur_controller
    joints:
      - joint_ur1
      - joint_ur2
      - joint_ur3
      - joint_ur4
      - joint_ur5
      - joint_ur6